services:

  projectsend:
    image: lscr.io/linuxserver/projectsend:latest
    container_name: projectsend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - ./data:/data 
    ports:
      - "8200:80"
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: mariadb-ps
    environment:
      MYSQL_ROOT_PASSWORD: projectsend
      MYSQL_DATABASE: projectsend
      MYSQL_USER: projectsend
      MYSQL_PASSWORD: projectsend
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped 

